name: unet_dwt
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - defaults
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2023.08.22
  - colorama=0.4.6
  - contourpy=1.0.5
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - icu=58.2
  - importlib_resources=5.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=12.15
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2020.4
  - munkres=1.1.4
  - numpy=1.22.4
  - openssl=3.0.10
  - packaging=23.1
  - pcre=8.45
  - pip=23.2.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.8.17
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pywavelets=1.4.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.2
  - tqdm=4.65.0
  - wheel=0.38.4
  - xz=5.4.2
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - antlr4-python3-runtime==4.8
      - appdirs==1.4.4
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - docker-pycreds==0.4.0
      - filelock==3.9.0
      - gitdb==4.0.10
      - gitpython==3.1.34
      - hydra-core==1.0.6
      - idna==3.4
      - jinja2==3.1.2
      - markupsafe==2.1.2
      - mpmath==1.2.1
      - networkx==3.0
      - omegaconf==2.0.6
      - pathtools==0.1.2
      - pillow==9.3.0
      - protobuf==4.24.2
      - psutil==5.9.5
      - pyyaml==6.0.1
      - requests==2.28.1
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sympy==1.11.1
      - torch==2.0.1+cu117
      - torchaudio==2.0.2+cu117
      - torchvision==0.15.2+cu117
      - typing-extensions==4.4.0
      - urllib3==1.26.13
      - wandb==0.15.10

